---
-
  hosts: web
  become: yes
  tasks:
    -
      name: "stop nginx"
      service:
        name: nginx
        state: stopped
    -
      name: "ensure ngnix is not installed"
      apt:
        name: nginx
        state: absent

