---
control:
    hosts:
        control-node:
            ansible_connection: local

web:
    hosts:
        web1:
            ansible_host: 192.168.56.11
    vars:
        ansible_become_user: root
        ansible_become_password: welcome1
        ansible_port: 22

db:
    hosts:
        db1:
            ansible_host: 192.168.56.12

all:
    vars:
        ansible_port: 7777
...
